name: CI Pipeline

on:
  pull_request:
    branches: 
    - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

