name: Deployment Pipeline
on:
    push:
        branches: 
            - main
jobs:
    deploy:
        name: Deploy App
        runs-on: ubuntu-latest
        environment: prod

        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Log Docker Into ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
    
            - name: Build, Tag And Push Docker Image
              env: 
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
                IMAGE_TAG: latest
              run: |
                docker build --target production -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

            - name: Trigger ECS Service Deployment
              env: 
                CLUSTER: ${{ secrets.AWS_ECS_CLUSTER }}
                SERVICE: ${{ secrets.AWS_ECS_SERVICE }}
                REGION: ${{ secrets.AWS_REGION }}
              run: |
                aws ecs update-service --cluster $CLUSTER --service $SERVICE --force-new-deployment --region $REGION

            - name: Deployment Completed
              env: 
                CLUSTER: ${{ secrets.AWS_ECS_CLUSTER }}
                SERVICE: ${{ secrets.AWS_ECS_SERVICE }}
                REGION: ${{ secrets.AWS_REGION }}
              run: |
                aws ecs wait services-stable --cluster $CLUSTER --services $SERVICE --region $REGION



